; File: src/sema.asm
; Purpose: Improve improve_code
; Project context:
;   This module implements the semantic analysis phase of the WebX compiler.
;   It analyzes the Abstract Syntax Tree (AST) generated by the parser and
;   performs semantic checks on the source code.

section .text
global sema
sema:
; Entry point for the semantic analysis phase
; Save the original stack pointer
    push rbp
    mov rbp, rsp

    ; Load the AST from memory
    mov rsi, [rdi + AST]
    mov rdi, [rdi + symtab]
    ; Initialize the semantic analysis variables
    mov rdx, [rdi + sema_vars]
    mov rcx, [rdi + scope_vars]

; Perform semantic checks on the AST
check_fn_decl:
    ; Check if the current node is a function declaration
    cmp [rsi + AST_node_type], byte 1
    je check_fn_signature
    ; If not, move to the next node
    mov rsi, [rsi + AST_next]
    jmp check_fn_decl

check_fn_signature:
    ; Check if the function signature is valid
    ; Check if the function has a valid return type
    cmp [rsi + AST_fn_ret_type], byte 0
    je invalid_fn_signature
    ; Check if the function has a valid parameter list
    cmp [rsi + AST_fn_param_list], byte 0
    je invalid_fn_signature

; Check if the function has a valid body
check_fn_body:
    ; Check if the function body is valid
    cmp [rsi + AST_fn_body], byte 0
    jl invalid_fn_signature

    ; Check if the function body is a block
    cmp [rsi + AST_fn_body_type], byte 1
    jne invalid_fn_body
    ; Check if the block has a valid statement list
    cmp [rsi + AST_block_stmt_list], byte 0
    je invalid_fn_body

    ; Check if the block has a valid return statement
    cmp [rsi + AST_block_return_stmt], byte 0
    je invalid_fn_body

    ; If the function body is valid, move to the next node
    mov rsi, [rsi + AST_next]
    jmp check_fn_decl

invalid_fn_signature:
    ; If the function signature is invalid, report an error
    mov rsi, [rdi + error_msg]
    mov rdx, [rsi + error_msg_len]
    mov rax, [rdi + error_code]
    mov [rdi + error_code], rax
    jmp exit_sema

invalid_fn_body:
    ; If the function body is invalid, report an error
    mov rsi, [rdi + error_msg]
    mov rdx, [rsi + error_msg_len]
    mov rax, [rdi + error_code]
    mov [rdi + error_code], rax
    jmp exit_sema

exit_sema:
; Exit the semantic analysis phase
; Restore the original stack pointer
    mov rsp, rbp
    pop rbp
    ret

section .data
error_msg db 'Error: invalid function signature', 0
error_msg_len equ $ - error_msg
error_code dd 0
AST dq 0
symtab dq 0
sema_vars dq 0
scope_vars dq 0